name: Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Build Results
      uses: actions/upload-artifact@v3
      with:
        name: build-results
        path: .

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@master
      with:
        name: build-results
        path: .
    - name: Run Tests
      run: dotnet test --no-build --logger trx --collect:"XPlat Code Coverage" --results-directory ./TestResults
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: TestResults/*.trx
        reporter: dotnet-trx
    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: .

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/download-artifact@master
      with:
        name: test-results
        path: .
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: TestResults/*/In/*/coverage.cobertura.xml
        format: markdown
        output: both
        badge: true
        fail_below_min: true
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        thresholds: '60 80'
