name: Build, Test and Publish

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Pack
      run: dotnet pack -c Release --no-build
    - name: Push generated package to nuget.org
      run: dotnet nuget push *.nupkg --skip-duplicate --no-symbols true -k ${API_KEY}
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}