name: Build, Test and Publish

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build-test.yml
    steps: 
    - uses: actions/download-artifact@master
      with:
        name: nuget
        path: .

    - name: Push generated package to nuget.org
      run: dotnet nuget push *.nupkg --skip-duplicate --no-symbols true -k ${API_KEY}
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}