name: Push

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  push:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build-test.yml@master
    steps: []
